# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/scx30g-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/scx30g-common/proprietary/bin/gpsd:system/vendor/bin/gpsd \
    vendor/samsung/scx30g-common/proprietary/bin/gps.cer:system/vendor/bin/gps.cer \
    vendor/samsung/scx30g-common/proprietary/lib/libsprd_agps_agent.so:system/vendor/lib/libsprd_agps_agent.so \
    vendor/samsung/scx30g-common/proprietary/lib/hw/gps.default.so:system/vendor/lib/hw/gps.default.so \
    vendor/samsung/scx30g-common/proprietary/lib/libfactoryutil.so:system/vendor/lib/libfactoryutil.so \
    vendor/samsung/scx30g-common/proprietary/lib/libatchannel.so:system/vendor/lib/libatchannel.so \
    vendor/samsung/scx30g-common/proprietary/lib/libatparser.so:system/vendor/lib/libatparser.so \
    vendor/samsung/scx30g-common/proprietary/vendor/firmware/vbc_eq:system/vendor/firmware/vbc_eq \
    vendor/samsung/scx30g-common/proprietary/bin/macloader:system/vendor/bin/macloader \
    vendor/samsung/scx30g-common/proprietary/bin/modemd:system/vendor/bin/modemd \
    vendor/samsung/scx30g-common/proprietary/bin/nvitemd:system/vendor/bin/nvitemd \
    vendor/samsung/scx30g-common/proprietary/bin/phoneserver:system/vendor/bin/phoneserver \
    vendor/samsung/scx30g-common/proprietary/bin/refnotify:system/vendor/bin/refnotify \
    vendor/samsung/scx30g-common/proprietary/bin/at_distributor:system/vendor/bin/at_distributor \
    vendor/samsung/scx30g-common/proprietary/bin/engpc:system/vendor/bin/engpc \
    vendor/samsung/scx30g-common/proprietary/bin/ext_data.sh:system/vendor/bin/ext_data.sh \
    vendor/samsung/scx30g-common/proprietary/bin/ext_kill.sh:system/vendor/bin/ext_kill.sh \
    vendor/samsung/scx30g-common/proprietary/bin/ext_symlink.sh:system/vendor/bin/ext_symlink.sh \
    vendor/samsung/scx30g-common/proprietary/lib/libreference-ril_sp.so:system/vendor/lib/libreference-ril_sp.so \
    vendor/samsung/scx30g-common/proprietary/lib/libsecnativefeature.so:system/vendor/lib/libsecnativefeature.so \
    vendor/samsung/scx30g-common/proprietary/lib/libomission_avoidance.so:system/vendor/lib/libomission_avoidance.so \
    vendor/samsung/scx30g-common/proprietary/lib/libomx_aacdec_sprd.so:system/vendor/lib/libomx_aacdec_sprd.so \
    vendor/samsung/scx30g-common/proprietary/lib/libomx_mp3dec_sprd.so:system/vendor/lib/libomx_mp3dec_sprd.so \
    vendor/samsung/scx30g-common/proprietary/lib/libomx_avcdec_hw_sprd.so:system/vendor/lib/libomx_avcdec_hw_sprd.so \
    vendor/samsung/scx30g-common/proprietary/lib/libomx_avcenc_hw_sprd.so:system/vendor/lib/libomx_avcenc_hw_sprd.so \
    vendor/samsung/scx30g-common/proprietary/lib/libomx_vpxdec_hw_sprd.so:system/vendor/lib/libomx_vpxdec_hw_sprd.so \
    vendor/samsung/scx30g-common/proprietary/lib/libomx_m4vh263dec_hw_sprd.so:system/vendor/lib/libomx_m4vh263dec_hw_sprd.so \
    vendor/samsung/scx30g-common/proprietary/lib/libomx_m4vh263enc_hw_sprd.so:system/vendor/lib/libomx_m4vh263enc_hw_sprd.so \
